# Generated by Django 3.0.4 on 2020-03-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
